app = "impostor-palabras-calanda"
primary_region = "mad"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["https://github.com/heroku/heroku-buildpack-nodejs"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1

  [[http_service.checks]]
    interval = "30s"
    grace_period = "10s"
    method = "GET"
    path = "/ping"
    protocol = "http"
    timeout = "5s"
    tls_skip_verify = false

  [[statics]]
    guest_path = "/public"
    url_prefix = "/"

[metrics]
  port = 8080
  path = "/metrics"
